version: '3'

services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
          - 15672:15672
          - 5672:5672
      volumes:
          - rabbitmq:/var/lib/rabbitmq
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongodb:
  rabbitmq:

networks:
  default:
    external:
      name: docker-network