version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Production

  database:
    image: postgres:9.6
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/9.6/main

volumes:
  postgres:

networks:
  default:
    external:
      name: docker-network
