version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Production

  mongodb:
    image: mongo:latest
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

volumes:
  db:

networks:
  default:
    external:
      name: docker-network