version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Production
        
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  db:

networks:
  default:
    external:
      name: docker-network